# Generated by Django 3.2.16 on 2022-10-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Master_Category',
        ),
    ]
